#spring:
#  profiles:
#    active: "production"

server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: "development"
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "production"
server:
  port: $PORT
---
spring:
  config:
    activate:
      on-profile: "heroku"

  main:
    web-application-type: "none"