spring:
  profiles:
    active: "heroku"

server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: "development"
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "production"
server:
  port: 0
---
spring:
  config:
    activate:
      on-profile: "heroku"

  main:
    web-application-type: "none"